version: '3.9'

networks:
  kong-net:
    driver: bridge

services:
  microservicesapp:
    image: microservicesapp
    networks:
      - kong-net
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
    links:
      - kong-database
      - kong-gateway
    environment:
      - FLASK_APP=app.py

  kong-database:
    image: postgres:9.6
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - 5432:5432
    restart: on-failure

  kong-migrations:
    image: kong/kong-gateway:2.8.1.4-alpine
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    restart: on-failure

  kong-gateway:
    image: kong/kong-gateway:2.8.1.4-alpine
    depends_on:
      - kong-migrations
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    restart: on-failure

  konga:
    image: pantsel/konga
    depends_on:
      - kong-gateway
    networks:
      - kong-net
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    links:
      - kong-gateway:kong-gateway
